image: Visual Studio 2015
branches:
  only:
    - source
    
environment:
  access_token:
    secure: 2Gib65Tz/4/pPXP29Yn598b42pM96vJbpvJa6gbJr8MzWna7EUfHO1UP3lI8Bu8i

install:
  - git submodule init
  - git submodule update --remote
  - cinst pretzel
  - cd _site
  - git branch -u origin/master master 
  - cd..

before_build:


build_script:
  - ps: .\pretzel.ps1

build: true

test: off

on_success:
  # See http://www.appveyor.com/docs/how-to/git-push for more info
  - git config --global credential.helper store
  - git config --global user.email %APPVEYOR_REPO_COMMIT_AUTHOR_EMAIL%
  - git config --global user.name %APPVEYOR_REPO_COMMIT_AUTHOR%
  - ps: Add-Content "$env:USERPROFILE\.git-credentials" "https://$($env:access_token):x-oauth-basic@github.com`n"
  - cmd: cd _site
  - git add .
  - git commit -m "From Appveyor [skip appveyor]"
  - git push origin HEAD:master -f